# Generated by Django 5.2.1 on 2026-03-06 13:07

import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('regular', 'Regular Membership'), ('associate', 'Associate Membership'), ('lifetime', 'Lifetime Membership'), ('student', 'Student Membership'), ('corporate', 'Corporate Membership')], default='regular', max_length=20)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validity_months', models.PositiveIntegerField(default=12)),
                ('benefits_description', models.TextField(blank=True)),
                ('has_voting_rights', models.BooleanField(default=True)),
                ('loan_eligible', models.BooleanField(default=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Max loan amount for this membership type', max_digits=14, null=True)),
                ('special_terms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('id_number', models.CharField(max_length=20)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('deceased', 'Deceased'), ('pending_renewal', 'Pending Renewal'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.membershiptype')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo', 'Member Photo'), ('id_front', 'ID Card (Front)'), ('id_back', 'ID Card (Back)'), ('kra_pin', 'KRA PIN Document'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=members.models.member_document_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
        ),
    ]
