# Generated by Django 5.2.12 on 2026-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_relationship',
        ),
        migrations.AddField(
            model_name='member',
            name='kvb_number',
            field=models.CharField(blank=True, help_text='Optional KVB registration number', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='document_type',
            field=models.CharField(choices=[('photo', 'Member Photo'), ('other', 'Other')], max_length=20),
        ),
    ]
