# Generated by Django 5.2.1 on 2026-03-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionpayment',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_payment', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='contributionpayment',
            name='contribution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.contributiontype'),
        ),
        migrations.AddField(
            model_name='monthlycontribution',
            name='contribution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.contributiontype'),
        ),
        migrations.AddField(
            model_name='monthlycontribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlycontribution',
            unique_together={('member', 'contribution_type', 'period')},
        ),
    ]
