"""
Django settings for ahtak project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment for production safety; fallback to existing key for local dev
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-%mdmv943hc3enqbh2lcs$c^%u-vz2!%hc97u!m0$ffy5$hi*%!'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Allow overriding DEBUG via environment variable (use 'False' on production)
DEBUG = os.environ.get('DEBUG', 'True').strip().lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,ahttak.or.ke,www.ahttak.or.ke",
).split(",") if h.strip()]

# URL of the frontend app (root redirect goes here)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://ahttak.or.ke')

# Configure CORS: allow all during DEBUG, otherwise permit the frontend origin(s)
from urllib.parse import urlparse

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []
else:
    CORS_ALLOW_ALL_ORIGINS = False
    parsed = urlparse(FRONTEND_URL)
    scheme = parsed.scheme or 'https'
    host = parsed.hostname or 'ahttak.or.ke'
    origins = [f"{scheme}://{host}"]
    # also allow www variant
    if not host.startswith('www.'):
        origins.append(f"{scheme}://www.{host}")
    # include local dev ports if explicitly set via env (keeps previous behavior optional)
    extra = os.environ.get('CORS_EXTRA_ALLOWED', '')
    if extra:
        origins.extend([o.strip() for o in extra.split(',') if o.strip()])
    CORS_ALLOWED_ORIGINS = origins

# Allow cookies/credentials (required when using SessionAuthentication)
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'True').strip().lower() in ('1', 'true', 'yes', 'on')

# Additional CORS settings: ensure headers and methods used by the frontend are permitted
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# If behind a reverse proxy (nginx) set this so Django knows request is secure
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# When running under HTTPS enforce secure cookies and optional redirect
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Allow cross-site cookies for SPA <-> API communication (requires HTTPS)
    SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'None')
    CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'None')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').strip().lower() in ('1', 'true', 'yes', 'on')

# CSRF trusted origins: include frontend and API domains by default
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "https://ahttak.or.ke,https://www.ahttak.or.ke",
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'core',
    'members',
    'events',
    'payments',
    'savings',
    'contributions',
    'notifications',
    'reports',
    'website',
]

# Jazzmin (modern Django admin theme)
JAZZMIN_SETTINGS = {
    "site_title": "AHTTAK Admin",
    "site_header": "Animal Health Technicians and Technologists Association (AHTTAK)",
    "site_brand": "AHTTAK",
    # Logo file currently lives at project root: BASE_DIR / "ahtklogo.png"
    "site_logo": "ahtklogo.png",
    "site_icon": "ahtklogo.png",
    "welcome_sign": "Welcome to AHTTAK administration",
    "copyright": "AHTTAK",
    "topmenu_links": [
        {"name": "Public site", "url": FRONTEND_URL, "new_window": True},
        {"name": "Dashboard", "url": "/admin/", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    # Disable UI builder to prevent runtime layout overrides persisting.
    "show_ui_builder": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "custom_css": "admin/theme-toggle.css",
    "custom_js": "admin/theme-toggle.js",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "website": "fas fa-globe",
        "website.sitesettings": "fas fa-cog",
        "website.heroslide": "fas fa-images",
        "website.teammember": "fas fa-user-tie",
        "website.blogpost": "fas fa-newspaper",
        "events.event": "fas fa-calendar-alt",
        "events.eventregistration": "fas fa-ticket-alt",
        "payments.payment": "fas fa-receipt",
        "members.member": "fas fa-id-card",
        "reports": "fas fa-chart-line",
    },
    "order_with_respect_to": ["auth", "website", "members", "events", "payments", "savings", "contributions", "reports"],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "default_theme_mode": "light",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'ahtak.middleware.SanitizeHostMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ahtak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ahtak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Use PostgreSQL. Set env vars: DB_NAME, DB_USER, DB_PASSWORD, DB_HOST (default localhost), DB_PORT (default 5432)

_db_engine = os.environ.get('DB_ENGINE', 'postgresql')
if _db_engine == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'ahtak'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR,  # so /static/ahtklogo.png is found
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Email (for notifications, welcome, approval)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@ahtak.local")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
# SMTP (used when EMAIL_BACKEND is django.core.mail.backends.smtp.EmailBackend)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

# Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    'membership-expiry-check': {
        'task': 'notifications.tasks.check_membership_expiry',
        'schedule': 86400.0,  # daily
    },
    'generate-monthly-contributions': {
        'task': 'contributions.tasks.generate_monthly_contributions',
        'schedule': 86400.0,  # daily; will create only missing month
    },
    'event-reminders': {
        'task': 'notifications.tasks.send_event_reminders',
        'schedule': 300.0,  # every 5 minutes
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# M-Pesa STK Push (Lipa Na M-Pesa Online)
# Get credentials from https://developer.safaricom.co.ke
# For sandbox: use test credentials from the portal
MPESA_ENV = os.environ.get('MPESA_ENV', 'sandbox')  
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', '')
MPESA_SHORTCODE = os.environ.get('MPESA_SHORTCODE', '')
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY', '')
# Callback URL must be HTTPS and publicly accessible (use ngrok for local dev)
MPESA_CALLBACK_URL = os.environ.get(
    'MPESA_CALLBACK_URL',
    'https://your-domain.com/api/payments/mpesa/callback/' if not DEBUG else ''
)
