# Generated by Django 5.2.1 on 2026-03-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('agenda', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('agm', 'AGM'), ('training', 'Training'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('social', 'Social Event')], default='seminar', max_length=20)),
                ('event_type', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='physical', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('map_link', models.URLField(blank=True)),
                ('venue_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('meeting_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet')], max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('max_attendees', models.PositiveIntegerField(default=0)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('early_bird_deadline', models.DateTimeField(blank=True, null=True)),
                ('membership_required', models.BooleanField(default=False)),
                ('max_guests_per_registration', models.PositiveIntegerField(default=0)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('organizer_name', models.CharField(blank=True, max_length=200)),
                ('organizer_contact', models.CharField(blank=True, max_length=100)),
                ('cpd_points', models.PositiveIntegerField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('price_member', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_non_member', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('early_bird_price_member', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_price_non_member', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('is_guest', models.BooleanField(default=False)),
                ('num_guests', models.PositiveIntegerField(default=0)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('amount_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='qr', max_length=20)),
                ('checked_in_by', models.CharField(blank=True, max_length=100)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='events.eventregistration')),
            ],
        ),
    ]
