# Generated by Django 5.2.12 on 2026-03-17 06:27

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('core_values', models.TextField(blank=True, help_text='One per line or paragraph')),
                ('objectives', models.TextField(blank=True)),
                ('constitution_file', models.FileField(blank=True, null=True, upload_to='website/about/')),
                ('governance_document', models.FileField(blank=True, null=True, upload_to='website/about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('form', 'Membership/Application Form'), ('plan', 'Strategic Plan'), ('report', 'Annual Report'), ('cpd', 'CPD Guidelines'), ('constitution', 'Constitution'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=website.models.download_file_path)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairperson_name', models.CharField(blank=True, max_length=200)),
                ('chairperson_title', models.CharField(blank=True, default='Chairperson', max_length=200)),
                ('chairperson_photo', models.ImageField(blank=True, null=True, upload_to='website/home/')),
                ('chairperson_message', models.TextField(blank=True)),
                ('intro_text', models.TextField(blank=True, help_text='Brief introduction to the association')),
                ('quick_links', models.JSONField(blank=True, default=list, help_text='[{"label":"Membership","url":"/register"},{"label":"Events","url":"/events"}]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('job_type', models.CharField(choices=[('job', 'Job Listing'), ('internship', 'Internship'), ('volunteer', 'Volunteer Opportunity'), ('tender', 'Tender / Project Call')], default='job', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('renewal_info', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Page Content',
                'verbose_name_plural': 'Membership Page Content',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('partners', models.TextField(blank=True, help_text='Collaborating organizations')),
                ('project_type', models.CharField(blank=True, help_text='e.g. Training Initiative, Donor-supported, Community Program', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/projects/')),
                ('external_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('guideline', 'Professional Guideline'), ('surveillance', 'Disease Surveillance Update'), ('publication', 'Publication/Research'), ('link', 'External Link')], default='guideline', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=website.models.resource_file_path)),
                ('external_url', models.URLField(blank=True, help_text='If link type, use this instead of file')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='region',
            field=models.CharField(blank=True, help_text='Region if Regional representative', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, help_text="Use 'Board', 'Management', 'Team', or 'Regional' to group on the About page.", max_length=100),
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='website/gallery/covers/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_albums', to='events.event')),
            ],
            options={
                'ordering': ['-created_at', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.gallery_media_path)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL for video type')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='website.galleryalbum')),
            ],
            options={
                'verbose_name_plural': 'Gallery media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
