# Generated by Django 5.2.1 on 2026-03-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_add_page_content_resources_downloads_jobs_projects_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_links',
            field=models.JSONField(blank=True, default=list, help_text='Footer links. Leave empty to use same as nav. [{"label":"Home","url":"/"},...]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_links',
            field=models.JSONField(blank=True, default=list, help_text='[{"label":"Home","url":"/"},{"label":"About","url":"/about"},{"label":"Events","url":"/events"},{"label":"Contact","url":"/contact"},{"label":"Join Us","url":"/register"}]'),
        ),
    ]
