# Generated by Django - populate default nav/footer links for SiteSettings

from django.db import migrations


def populate_nav_links(apps, schema_editor):
    SiteSettings = apps.get_model("website", "SiteSettings")
    obj = SiteSettings.objects.filter(pk=1).first()
    if obj and (not obj.nav_links or len(obj.nav_links) == 0):
        default_nav = [
            {"label": "Home", "url": "/"},
            {"label": "About", "url": "/about"},
            {"label": "Membership", "url": "/membership"},
            {"label": "CPD", "url": "/cpd"},
            {"label": "Events", "url": "/events"},
            {"label": "Resources", "url": "/resources"},
            {"label": "Downloads", "url": "/downloads"},
            {"label": "Jobs", "url": "/jobs"},
            {"label": "Projects", "url": "/projects"},
            {"label": "Gallery", "url": "/gallery"},
            {"label": "News", "url": "/blog"},
            {"label": "Contact", "url": "/contact"},
            {"label": "Join Us", "url": "/register"},
            {"label": "Sign In", "url": "/login"},
        ]
        obj.nav_links = default_nav
        obj.footer_links = default_nav
        obj.save()


def reverse_populate(apps, schema_editor):
    SiteSettings = apps.get_model("website", "SiteSettings")
    obj = SiteSettings.objects.filter(pk=1).first()
    if obj:
        obj.nav_links = []
        obj.footer_links = []
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_add_nav_footer_links"),
    ]

    operations = [
        migrations.RunPython(populate_nav_links, reverse_populate),
    ]
