# Generated by Django 5.2.1 on 2026-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_populate_default_nav_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcements',
            field=models.JSONField(blank=True, default=list, help_text='Running message items. ["Welcome to AHTTAK", "Notice 1", "Notice 2"]. Shown in top ticker.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_sections',
            field=models.JSONField(blank=True, default=list, help_text='[{"title":"Quick Links","links":[{"label":"Payment","url":"/pay"}]},{"title":"Support","links":[]}]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g. Upholding Professional Standards', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Animal Health Technicians and Technologists Association (AHTTAK)', max_length=200),
        ),
    ]
