# Generated by Django 5.2.1 on 2026-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_populate_default_footer_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_slides',
            field=models.JSONField(blank=True, default=list, help_text='Home page hero carousel slides. Example: [{"image":"/media/hero.jpg","title":"Our Mandate","subtitle":"...","cta_label":"Learn More","cta_url":"/about"}]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='announcements',
            field=models.JSONField(blank=True, default=list, help_text='Top ticker items. Supports either strings (legacy) or objects like: [{"text":"Welcome to AHTTAK","url":"/about"},{"text":"Download form","file":"/media/x.pdf"}]'),
        ),
    ]
