# Generated by Django 5.2.1 on 2026-03-17 07:49

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_add_hero_slides_clickable_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.hero_slide_path)),
                ('title', models.CharField(blank=True, help_text='Optional - shown on slide', max_length=200)),
                ('link_url', models.CharField(blank=True, help_text="Optional - 'Learn more' links here", max_length=500)),
                ('link_label', models.CharField(blank=True, default='Learn more »', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
