# Generated by Django 5.2.1 on 2026-03-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('registration', 'Registration Fee'), ('membership', 'Membership Fee'), ('renewal', 'Membership Renewal'), ('event', 'Event Registration Fee'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('loan_processing', 'Loan Processing Fee'), ('loan_repayment', 'Loan Repayment'), ('share_purchase', 'Share Capital Purchase'), ('share_redemption', 'Share Redemption'), ('contribution', 'Monthly Contribution'), ('penalty', 'Penalty/Fine'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.eventregistration')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
