# Generated by Django 5.2.12 on 2026-03-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_mpesa_transactions', to='events.eventregistration')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_mpesa_transactions', to='members.member')),
            ],
        ),
    ]
